apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
        app: test-deployment

    spec:
      containers:
        - name: test-deployment
          image: le999/ts_example:1.0
          ports:
            - name: http
              containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: test-deployment-lb
spec:
  selector:
    name: test-deployment
  ports:
    - name: "3000"
      port: 3000
      nodePort: 30009
  type: LoadBalancer

